name: CMake Build - Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
strategy:
  matrix:
    compiler: [gcc, clang]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: 'latest'

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        run: cmake -B ./build -S ./
        env:
          CC: clang

      - name: Build
        run: cmake --build ./build --config Release

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifacts
          path: build/udpfwd.exe
